# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: defs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndefs.proto\"*\n\rStoreKeyValue\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x17\n\x08GetValue\x12\x0b\n\x03key\x18\x01 \x01(\t\" \n\x10GetValueResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"-\n\tDeleteKey\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65leteValue\x18\x02 \x01(\x08\"\x15\n\x06\x41\x64\x64Key\x12\x0b\n\x03key\x18\x01 \x03(\t\"\xa1\x01\n\x10\x44\x61tastoreRequest\x12\'\n\rstoreKeyValue\x18\x01 \x01(\x0b\x32\x0e.StoreKeyValueH\x00\x12\x1d\n\x08getValue\x18\x02 \x01(\x0b\x32\t.GetValueH\x00\x12\x1f\n\tdeleteKey\x18\x03 \x01(\x0b\x32\n.DeleteKeyH\x00\x12\x19\n\x06\x61\x64\x64Key\x18\x04 \x01(\x0b\x32\x07.AddKeyH\x00\x42\t\n\x07request\"\xa0\x01\n\x11\x44\x61tastoreResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.DatastoreResponse.ResponseStatus\x12-\n\x10getValueResponse\x18\x02 \x01(\x0b\x32\x11.GetValueResponseH\x00\"\x1d\n\x0eResponseStatus\x12\x0b\n\x07SUCCESS\x10\x00\x42\n\n\x08response\"\x80\x02\n\rausf_ue_s_enc\x12\x0e\n\x06\x63tx_id\x18\x01 \x01(\t\x12\x0c\n\x04suci\x18\x02 \x01(\t\x12\x0c\n\x04supi\x18\x03 \x01(\t\x12\x1c\n\x14serving_network_name\x18\x04 \x01(\t\x12\x11\n\tauth_type\x18\x05 \x01(\x05\x12\x17\n\x0f\x61uth_events_url\x18\x06 \x01(\t\x12\x13\n\x0b\x61uth_result\x18\x07 \x01(\x05\x12\x0c\n\x04rand\x18\x08 \x01(\x0c\x12\x11\n\txres_star\x18\t \x01(\x0c\x12\x12\n\nhxres_star\x18\n \x01(\x0c\x12\r\n\x05kausf\x18\x0b \x01(\x0c\x12\r\n\x05kseaf\x18\x0c \x01(\x0c\x12\x11\n\tfsm_state\x18\r \x01(\tb\x06proto3')



_STOREKEYVALUE = DESCRIPTOR.message_types_by_name['StoreKeyValue']
_GETVALUE = DESCRIPTOR.message_types_by_name['GetValue']
_GETVALUERESPONSE = DESCRIPTOR.message_types_by_name['GetValueResponse']
_DELETEKEY = DESCRIPTOR.message_types_by_name['DeleteKey']
_ADDKEY = DESCRIPTOR.message_types_by_name['AddKey']
_DATASTOREREQUEST = DESCRIPTOR.message_types_by_name['DatastoreRequest']
_DATASTORERESPONSE = DESCRIPTOR.message_types_by_name['DatastoreResponse']
_AUSF_UE_S_ENC = DESCRIPTOR.message_types_by_name['ausf_ue_s_enc']
_DATASTORERESPONSE_RESPONSESTATUS = _DATASTORERESPONSE.enum_types_by_name['ResponseStatus']
StoreKeyValue = _reflection.GeneratedProtocolMessageType('StoreKeyValue', (_message.Message,), {
  'DESCRIPTOR' : _STOREKEYVALUE,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:StoreKeyValue)
  })
_sym_db.RegisterMessage(StoreKeyValue)

GetValue = _reflection.GeneratedProtocolMessageType('GetValue', (_message.Message,), {
  'DESCRIPTOR' : _GETVALUE,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:GetValue)
  })
_sym_db.RegisterMessage(GetValue)

GetValueResponse = _reflection.GeneratedProtocolMessageType('GetValueResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETVALUERESPONSE,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:GetValueResponse)
  })
_sym_db.RegisterMessage(GetValueResponse)

DeleteKey = _reflection.GeneratedProtocolMessageType('DeleteKey', (_message.Message,), {
  'DESCRIPTOR' : _DELETEKEY,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:DeleteKey)
  })
_sym_db.RegisterMessage(DeleteKey)

AddKey = _reflection.GeneratedProtocolMessageType('AddKey', (_message.Message,), {
  'DESCRIPTOR' : _ADDKEY,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:AddKey)
  })
_sym_db.RegisterMessage(AddKey)

DatastoreRequest = _reflection.GeneratedProtocolMessageType('DatastoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATASTOREREQUEST,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:DatastoreRequest)
  })
_sym_db.RegisterMessage(DatastoreRequest)

DatastoreResponse = _reflection.GeneratedProtocolMessageType('DatastoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATASTORERESPONSE,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:DatastoreResponse)
  })
_sym_db.RegisterMessage(DatastoreResponse)

ausf_ue_s_enc = _reflection.GeneratedProtocolMessageType('ausf_ue_s_enc', (_message.Message,), {
  'DESCRIPTOR' : _AUSF_UE_S_ENC,
  '__module__' : 'defs_pb2'
  # @@protoc_insertion_point(class_scope:ausf_ue_s_enc)
  })
_sym_db.RegisterMessage(ausf_ue_s_enc)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOREKEYVALUE._serialized_start=14
  _STOREKEYVALUE._serialized_end=56
  _GETVALUE._serialized_start=58
  _GETVALUE._serialized_end=81
  _GETVALUERESPONSE._serialized_start=83
  _GETVALUERESPONSE._serialized_end=115
  _DELETEKEY._serialized_start=117
  _DELETEKEY._serialized_end=162
  _ADDKEY._serialized_start=164
  _ADDKEY._serialized_end=185
  _DATASTOREREQUEST._serialized_start=188
  _DATASTOREREQUEST._serialized_end=349
  _DATASTORERESPONSE._serialized_start=352
  _DATASTORERESPONSE._serialized_end=512
  _DATASTORERESPONSE_RESPONSESTATUS._serialized_start=471
  _DATASTORERESPONSE_RESPONSESTATUS._serialized_end=500
  _AUSF_UE_S_ENC._serialized_start=515
  _AUSF_UE_S_ENC._serialized_end=771
# @@protoc_insertion_point(module_scope)
